config/routes.rb
CupidiconProduct::Application.routes.draw do

  get "submissions/new"
  
   get "user/available"

  get "user/engaged"

  get "assignments/reauthorization"

  get "assignments/resubmit"

  get "assignments/revision"

  get "assignments/published"

  get "assignments/authorize"

  get "assignments/write"

  devise_for :users

  resources :users, only: [:show] # create a route for users#show

  resources :assignments do 
    resource :submissions
  end

  match "need_content" => 'welcome#need_content', via: :get

  match "write_content" => 'welcome#write_content', via: :get

  match "loves_lexicon" => 'welcome#loves_lexicon', via: :get

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'

  post "assignments/:id/renew", to: 'assignments#renew'

  post "assignments/:id/cancel", to: 'assignments#cancel'

  post "assignments/:id/write", to: 'assignments#write'

  post "assignments/:id/authorize", to: 'assignments#authorize'

  post "assignments/:id/published", to: 'assignments#published'

  post "assignments/:id/reject", to: 'assignments#reject'

  post "assignments/:id/resubmit", to: 'assignments#resubmit'

  post "assignments/:id/revision", to: 'assignments#revision'

  post "assignments/:id/reauthorization", to: 'assignments#reauthorization'

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  has_many :transactions
  has_many :submissions
  attr_accessible :body, :category, :cost, :instructions, :key_words, :language, :rating, :style, :title, :word_count, :description

  default_scope order('created_at DESC')

  def self.published
    where(state: 6)
  end

  def self.authorization
    where(state: 3)
  end

  def self.revision
    where(state: 4)
  end

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true  
  validates :user, presence: true

  state_machine initial: :open do
    state :open, value: 0
    state :review, value: 1
    state :write, value: 2
    state :authorization, value: 3
    state :revision, value: 4
    state :resubmit, value: 5   
    state :published, value: 6

  event :review do
      transition :open => :review
    end

    event :renew do 
      transition :review => :open
    end
   
    event :write do 
      transition :review => :write
    end

    event :cancel do 
      transition :write => :open
    end

    event :authorization do 
      transition :write => :authorization
    end

    event :published do
      transition :authorization => :published
    end

    event :reject do 
      transition :authorization => :open
    end

    event :revision do
      transition :authorization => :revision
    end

    event :resubmit do
      transition :revision => :resubmit
    end

    event :revision do
      transition :resubmit => :revision
    end

    event :published do
      transition :resubmit => :published
    end

    event :cancel do 
      transition :revision => :open
    end

    event :reject do 
      transition :resubmit => :open
    end  
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  def index
    @assignments = Assignment.where(state: 0)
  end

  def show
    @assignment = Assignment.find(params[:id])
    if @assignment.state == 0
      if @assignment.transactions.where(writer_id: @assignment.user_id, transaction_type: "review").length > 2
        flash[:notice] = "You can no longer review this assignment"
        redirect_to assignments_path
      else
         @assignment.review 
        # Change the current user's state
        @assignment.transactions.create(transaction_type: "review", writer_id: @assignment.user_id)
      end
    else
      flash[:notice] = "That assignment is currently being reviewed by another writer"
      redirect_to assignments_path
    end
  end

  def new
    @assignment = Assignment.new
    authorize! :create, Assignment, message: "You need to be a member to create a new assignment."
  end

  def create
  @assignment = current_user.assignments.build(params[:assignment])  
  authorize! :create, @assignment, message: "You need to be signed up to do that."
  if @assignment.save
    flash[:notice] = "Assignment was saved."
    redirect_to user_path(current_user.id)
  else
    flash[:error] = "There was an error saving the Assignment. Please try again."
    render :new
  end
end

  def edit
    @assignment = Assignment.find(params[:id])
    authorize! :edit, @assignment, message: "You need to own the assignment to edit it."
  end

  def update
    @assignment = Assignment.find(params[:id])
    authorize! :edit, @assignment, message: "You need to own the assignment to edit it."
    if @assignment.update_attributes(params[:assignment])
      flash[:notice] = "Assignment was updated."
      redirect_to @assignment
    else
      flash[:error] = "There was an error saving the Assignment. Please try again."
      render :new
    end
  end

  def renew
    @assignment = Assignment.find(params[:id])
    @assignment.renew
    @assignment.transactions.create(transaction_type: "renew", writer_id: @assignment.user_id)
    redirect_to assignments_path
  end

  def write  
    @assignment = Assignment.find(params[:id])
    @submission = @assignment.submissions.new
    @assignment.write
    @assignment.transactions.create(transaction_type: "write", writer_id: @assignment.user_id)        
  end

  def cancel
    @assignment = Assignment.find(params[:id])
    if @assignment.cancel
      @assignment.transactions.create(transaction_type: "cancel", writer_id: @assignment.user_id)
      flash[:notice] = "You can only review this assignment 1 more time."
      redirect_to assignments_path
    else
      flash[:error] = "Something went wrong."
      redirect_to assignments_path
    end
  end


  def authorize
    @submission = Submission.find(params[:id])
    @assignment = @submission.assignment
    if @assignment.authorization
      @assignment.transactions.create(transaction_type: "authorize", writer_id: @assignment.user_id)
      flash[:notice] = "Assignment was submited for review by client."
      redirect_to user_path(current_user.id)
    else
      flash[:error] = "There was a problem submitting the assignment. Please try again"
      redirect_to @assignment
    end
  end
 
  def published
    @assignment = Assignment.find(params[:id])
    @assignment.published
    @assignment.transactions.create(transaction_type: "published", writer_id: @assignment.user_id)
  end

  def reject
    @assignment = Assignment.find(params[:id])
    @assignment.reject
    @assignment.transactions.create(transaction_type: "reject", writer_id: @assignment.user_id)
    redirect_to assignments_path
  end

  def revision
    @assignment = Assignment.find(params[:id])
    @assignment.revision
    @assignment.transactions.create(transaction_type: "revision", writer_id: @assignment.user_id)
  end

  def resubmit
    @assignment = Assignment.find(params[:id])
    @assignment.resubmit
    @assignment.transactions.create(transaction_type: "resubmit", writer_id: @assignment.user_id)
  end

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/authorize.html.erb
<h3>Assignment Authorization</h3>
<p>An author has fulfilled your requested assignment. Please accept or reject accordingly. You can also request the author to rewrite the assignment if desired. Please specify any changes that need to be made.</p>

<strong>Author's submission</strong>

<div class="media"> 
  <div class="media-body">
    <div class="row">
      <div class="span12">
        <div class="thumbnail">      
          <h4><%= @assignment.title %></h4>
            <p><%= @assignment.body %></p>
          </div>          
        </div>
      </div>
       </div> 
  </div>
  <br>      
      <table>
              <tr>
              <td><%= form_tag("/assignments/#{@assignment.id}/published") do %>
                  <%= submit_tag 'Accept' %>
              <% end %>
              </td>
              <td><%= form_tag("revision") do %>
                  <%= submit_tag 'Revision' %>
              <% end %>
              </td>
              <td><%= form_tag("reject") do %>
                  <%= submit_tag 'Reject' %>
              <% end %>
              </td>
              </tr>      
            </table>
    


app/views/assignments/confirm.html.erb
<h1>Assignments#confirm</h1>
<p>Find me in app/views/assignments/confirm.html.erb</p>
<div class="media"> 
  <div class="media-body">
    <div class="row">
      <div class="span12">
        <div class="thumbnail">      
          <h4><%= @assignment.title %></h4>
            <p><%= @assignment.body %></p>
            <p><%= @assignment.word_count %></p>
            <p><%= @assignment.language %></p>
            <p><%= @assignment.rating %></p>
            <p><%= @assignment.key_words %></p>
            <p><%= @assignment.cost %></p>
            <p><%= @assignment.style %></p>
            <p><%= @assignment.instructions %></p>  
          </div>          
        </div>
      </div>
    </div> 
  </div>

app/views/assignments/edit.html.erb
<h1>Edit Assignment</h1>
<div class="row">
  <div class="span4">
    <p>Guidelines for new assignments:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { assignment: @assignment } %>
  </div>
</div>

app/views/assignments/index.html.erb
<h3>All Assignments</h3>

<p>Please select one of the assignments below to review. You can only review an assignment twice.</p>
<hr>
<div>
<% if can? :create, Assignment %>
<%= link_to "New Assignment", new_assignment_path, class: 'btn btn-primary btn-mini' %>
<% end %>
</div>

<% @assignments.each do |assignment| %>
 
<div class="media"> 
  <div class="media-body">
    <div class="row">
      <div class="span12">
        <div class="thumbnail">      
          <h5><%= link_to assignment.title, assignment %></h5>
            <small>
                submitted <%= time_ago_in_words(assignment.created_at) %> ago by <%= assignment.user.name %><br/>                 
            </small> 
            <p><%= assignment.cost %></P> 
            <p><%= assignment.rating %></P>    
          </div>
        </div>
      </div>
    </div> 
  </div>
<% end %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<div class="row">
  <div class="span-6">
    <p>Guidelines for new assignments:</p>
    <ul>
      <li>Make sure title is appropriate.</li>
      <li>Provide a description for your assignment.</li>
      <li>Choose the category you would like.</li>
      <li>Indicate how many words.</li>
      <li>Make sure title is appropriate.</li>
      <li>Provide a description for your assignments.</li>
      <li>Make sure title is appropriate.</li>
      <li>Provide a description for your assignment.</li>
    </ul>
  </div>
  <div class="span-6">
    <%= form_for @assignment, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group"> 
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="control-group">
            <%= f.label :body, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_area :body, rows: 2 %>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :category, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_field :category %>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :word_count, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_field :word_count %>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :language, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_field :language %>
              </div>
          </div>          
          <div class="control-group">
            <%= f.label :rating, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_field :rating %>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :key_words, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_field :key_words %>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :cost, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_field :cost %>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :style, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_field :style %>
              </div>
          </div>
          <div class="control-group">
            <%= f.label :instructions, class: 'control-label' %>
              <div class="controls">
                  <%= f.text_area :instructions, rows: 2 %>
              </div>
          </div>
          <div class="control-group">
            <div class="controls">
                <%= f.submit "Save", class: 'btn' %>
            </div>
          </div>
      <% end %>
    </div>
</div>

app/views/assignments/published.html.erb
<h1>Assignment Published</h1>
<p>You have accepted the authors assignment and this has subsequently been published. The author will now be paid accordingly from your account</p>

<p>Thank you for using Cupidicon!</p>

app/views/assignments/resubmit.html.erb
<h1>Assignment Resubmit</h1>
<p>An author has fulfilled your requested revision. Please accept or reject accordingly. You can also request the author to rewrite the assignment if desired. Please specify any changes that need to be made below.</p>

<div class="media"> 
  <div class="media-body">
    <div class="row">
      <div class="span12">
        <div class="thumbnail">      
          <h4><%= @assignment.title %></h4>
            <p><%= @assignment.body %></p>
            <p><%= @assignment.word_count %></p>
            <p><%= @assignment.language %></p>
            <p><%= @assignment.rating %></p>
            <p><%= @assignment.key_words %></p>
            <p><%= @assignment.cost %></p>
            <p><%= @assignment.style %></p>
            <p><%= @assignment.instructions %></p>  
          </div>          
        </div>
      </div>
      <p>
      <table>
              <tr>
              <td><%= form_tag("/assignments/#{@assignment.id}/published") do %>
                  <%= submit_tag 'Accept' %>
              <% end %>
              </td>
              <td><%= form_tag("revision") do %>
                  <%= submit_tag 'Revision' %>
              <% end %>
              </td>
              <td><%= form_tag("reject") do %>
                  <%= submit_tag 'Reject' %>
              <% end %>
              </td>
              </tr>      
            </table>


app/views/assignments/revision.html.erb
<h1>Assignment Revision</h1>
<p>The client has requested a rewrite for this assignment. Please read the notes carefully and resubmit accordingly.</p>

<p>Alternatively, you can cancel the assignment and let another author attempt it.</p>

<div class="media"> 
  <div class="media-body">
            <%= simple_form_for @assignment do |f| %>
          <%= f.input :body, :as => :text, :input_html => { class: 'test', :cols => 150, :rows => 15 } %>
          <% end %>
      </div>
    </div>
      <p>
      <table>
              <tr>
              <td><%= form_tag("/assignments/#{@assignment.id}/resubmit") do %>
                  <%= submit_tag 'Resubmit' %>
              <% end %>
              </td>
              <td><%= form_tag("cancel") do %>
                  <%= submit_tag 'Cancel' %>
              <% end %>
              </td>
              </tr>      
            </table>







app/views/assignments/show.html.erb
<h3>Review Assignment</h3>

<p style="text-align: justify;">The assignment below is currently available to write. The client will often provide specific instructions. Please ensure you read the instructions and understand their requirements before electing to write this assignment.</p>

<p>Alternatively, you can elect to cancel the assignment, but you will only be allowed to select this assignment once more.</p>

<strong>You have 10 minutes to accept this assignment</strong>


<div class="media"> 
  <div class="media-body">
    <div class="row">
      <div class="span12">
        <div class="thumbnail">      
          <table class="table table-condensed table-striped">
          <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Word Count</th> 
          <th>Language</th>
          <th>Rating</th>
          <th>Key Words</th>
          <th>Price</th>
          <th>Style</th>
          <th>Instructions</th>
          </tr>

          <tr>
          <td><%= @assignment.title %></td>
              <td><%= @assignment.body %></td>
              <td><%= @assignment.word_count %></td>
              <td><%= @assignment.language %></td>
              <td><%= @assignment.rating %></td>
              <td><%= @assignment.key_words %></td>
              <td><%= @assignment.cost %></td>
              <td><%= @assignment.style %></td>
              <td><%= @assignment.instructions %></td>
              </tr> 
                    
            </table>   
        </div>
      </div>
    </div>
    <p> 
    <table>
              <tr>
              <td><%= form_tag("#{@assignment.id}/renew") do %>
                  <%= submit_tag 'Cancel' %>
              <% end %>
              </td>
              
              <td>
                <%= form_tag("#{@assignment.id}/submissions/new", method: "get") do %>
                  <%= submit_tag 'Write' %>
                 
                    <% end %>
              </td>

              </tr>      
            </table>    
  </div>
</div>

app/views/assignments/write.html.erb
<h3>Write Assignment</h3>



<p style="text-align: justify;">You have elected to write this assignment. Please read the requirements carefully. Once you have written the assignment it will be reviewed by the client. They may request a revision so please check your assignment status regularly. Should they accept your submission you will be paid the agreed amount accordingly.</p>

<p>Alternatively, you can elect to cancel the assignment, but you will only be allowed to select this assignment once more.</p>

<hr>

<div class="media"> 
  <div class="media-body">
    <div class="row">
      <div class="span12">
        <div class="thumbnail">
        <table class="table table-condensed table-striped">
          <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Word Count</th> 
          <th>Language</th>
          <th>Rating</th>
          <th>Key Words</th>
          <th>Price</th>
          <th>Style</th>
          <th>Instructions</th>
          </tr>

          <tr>
          <td><%= @assignment.title %></td>
              <td><%= @assignment.body %></td>
              <td><%= @assignment.word_count %></td>
              <td><%= @assignment.language %></td>
              <td><%= @assignment.rating %></td>
              <td><%= @assignment.key_words %></td>
              <td><%= @assignment.cost %></td>
              <td><%= @assignment.style %></td>
              <td><%= @assignment.instructions %></td>
              </tr>              
            </table>    
          </div>
        </div>
      </div>
      <br>
      <div>
      
    <table>
      <tr>
       <td>
         <%= form_tag("cancel") do %>
           <%= submit_tag 'Cancel' %>    
         <% end %>
       </td>
       <td>
         
           <%= f.submit 'Submit' %>
         <% end %>
       </td>
       </tr>      
     </table>
   </div>
 </div>

