config/routes.rb
CupidiconProduct::Application.routes.draw do

  get "submissions/new"
  
   get "user/available"

  get "user/engaged"

  get "assignments/reauthorization"

  get "assignments/resubmit"

  get "assignments/revision"

  get "assignments/published"

  get "assignments/authorize"

  get "assignments/write"

  devise_for :users

  resources :users, only: [:show] # create a route for users#show

  resources :assignments do 
    resource :submissions
  end

  match "need_content" => 'welcome#need_content', via: :get

  match "write_content" => 'welcome#write_content', via: :get

  match "loves_lexicon" => 'welcome#loves_lexicon', via: :get

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'

  post "assignments/:id/renew", to: 'assignments#renew'

  post "assignments/:id/cancel", to: 'assignments#cancel'

  post "assignments/:id/write", to: 'assignments#write'

  post "assignments/:id/authorize", to: 'assignments#authorize'

  post "assignments/:id/published", to: 'assignments#published'

  post "assignments/:id/reject", to: 'assignments#reject'

  post "assignments/:id/resubmit", to: 'assignments#resubmit'

  post "assignments/:id/revision", to: 'assignments#revision'

  post "assignments/:id/reauthorization", to: 'assignments#reauthorization'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :avatar
  # attr_accessible :title, :body

  has_many :assignments

  has_many :submissions, foreign_key: :writer_id

  before_create :set_member

  mount_uploader :avatar, AvatarUploader

  ROLES = %w[member moderator admin]
def role?(base_role)
  role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
end

private 

def set_member
  self.role = 'member'
end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @revision_assignments = Assignment.revision.where(user_id: @user.id)
    @published_assignments = Assignment.published.where(user_id: @user.id)
    @authorize_assignments = Assignment.authorization.where(user_id: @user.id)     
  end

end

app/views/users/show.html.erb
<div class="row">
  <div class="span12">
    <div class="media">
      <% if @user.avatar? %>
        <%= image_tag @user.avatar.url, class: 'pull-left' %>
      <% end %>
      <div class="media-body">
        <h2 class="media-heading"><%= @user.name %></h2>
        <small>
          <%= pluralize(@user.assignments.count, 'assignment') %>
          
        </small>
      </div>
    </div>
  </div>
</div>

<br/>

<div class="row">
  <div class="tabbable">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#assignments" data-toggle="tab">Assignments</a></li>
      <li><a href="#revision" data-toggle="tab">Revision</a></li>
      <li><a href="#published" data-toggle="tab">Published</a></li>
      <li><a href="#authorization" data-toggle="tab">Authorization</a></li>
      <li><a href="#comments" data-toggle="tab">Comments</a></li>
      <li><a href="#account" data-toggle="tab">Account</a></li>
      
    </ul>
    

      <div class="tab-pane active" id="assignments">
        <% @user.assignments.each do |assignment| %>
          <p><%= link_to assignment.title, assignment_path(assignment.id) %></p>
        <% end %>
      </div>
      <div class="tab-pane" id="revision">
       <% @revision_assignments.each do |assignment| %>
          <p><%# link_to assignment.title, assignment_path(assignment.id) %></p>
        <% end %> 
      </div>
      <div class="tab-pane" id="published">
        <% @published_assignments.each do |assignment| %>
          <p><%= link_to assignment.title, assignment_path(assignment.id) %></p>
        <% end %>
      </div>
      <div class="tab-pane" id="authorization">
        <% @authorize_assignments.each do |assignment| %>
          <p><%= link_to assignment.title, assignment_path(assignment.id) %></p>
          <p>Test</p>
        <% end %>
      </div>
      <div class="tab-pane" id="comments">
        
      </div>   
      <div class="tab-pane" id="account">
        
      </div>    
  </div>
</div>