config/routes.rb
CupidiconProduct::Application.routes.draw do

  get "submissions/new"
  
   get "user/available"

  get "user/engaged"

  get "assignments/reauthorization"

  get "assignments/resubmit"

  get "assignments/revision"

  get "assignments/published"

  get "assignments/authorize"

  get "assignments/write"

  devise_for :users

  resources :users, only: [:show] # create a route for users#show

  resources :assignments do 
    resource :submissions
  end

  match "need_content" => 'welcome#need_content', via: :get

  match "write_content" => 'welcome#write_content', via: :get

  match "loves_lexicon" => 'welcome#loves_lexicon', via: :get

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'

  post "assignments/:id/renew", to: 'assignments#renew'

  post "assignments/:id/cancel", to: 'assignments#cancel'

  post "assignments/:id/write", to: 'assignments#write'

  post "assignments/:id/authorize", to: 'assignments#authorize'

  post "assignments/:id/published", to: 'assignments#published'

  post "assignments/:id/reject", to: 'assignments#reject'

  post "assignments/:id/resubmit", to: 'assignments#resubmit'

  post "assignments/:id/revision", to: 'assignments#revision'

  post "assignments/:id/reauthorization", to: 'assignments#reauthorization'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <title>Cupidicon Product</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= image_tag("cupidicon_logo.jpg") %>
    <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Need Content?", need_content_path %></li>
        <li><%= link_to "Write Content", write_content_path %></li>
        <li><%= link_to "Love's Lexicon", assignments_path %></li>        
        <li><%= link_to "About", about_path %></li>

        <div class="pull-right user-info">
          <% if current_user %>
          <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
            Hello <%= link_to (current_user.name || current_user.email), current_user %>!
            <%= link_to edit_user_registration_path, class: 'btn btn-mini' do %>
              <i class="icon-user"></i>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-mini' do %>
              <i class="icon-share-alt"> </i>
            <% end %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or 
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
    </ul>

    <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

<%= yield %>
</div>


</body>
</html>